blank_issues_enabled: false
contact_links:
  - name: SmashMC Website
    url: https://pokesmash.enjin.com/
    about: The SmashMC website
  - name: SmashMC Discord
    url: https://discord.gg/smashmc
    about: The SmashMC Discord
